# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test0():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_0(self):
    self.driver.get("https://adminqa.neapro.site/users")
    self.driver.set_window_size(1154, 880)
    self.driver.find_element(By.LINK_TEXT, "Последняя »").click()
    self.driver.find_element(By.LINK_TEXT, "75").click()
    self.driver.find_element(By.CSS_SELECTOR, "#user_119 .view_link").click()
    self.driver.find_element(By.CSS_SELECTOR, "#documents_passport_96 a:nth-child(3)").click()
    assert self.driver.switch_to.alert.text == "Вы уверены, что хотите удалить это?"
    self.driver.switch_to.alert.accept()
  
